version: '3.5'
name: makhzan

services:
  backend:
    build: .
    container_name: makhzan-api
    restart: unless-stopped
    image: registry.gitlab.com/alayoubifaek/makhzan/makhzan/api:latest
    env_file: .env
    networks:
      - master
    ports:
      - 8000:3000
    depends_on:
      - db
    volumes:
      - storage_volume:/home/app/uploads

  db:
    image: mysql:8.0
    container_name: makhzan-database
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=makhzan
    networks:
      - master
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    env_file: .env
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=""
      - MYSQL_ROOT_PASSWORD=""
      - PMA_HOST=db
    ports:
      - 6543:80
    networks:
      - master
    depends_on:
      db:
        condition: service_healthy

networks:
  master:
    name: makhzan-network

volumes:
  makhzan_storage_volume:
    name: makhzan_storage_volume